name: analyzer_plugin
description: A framework and support code for building plugins for the analysis server.
version: 0.11.1
repository: https://github.com/dart-lang/sdk/tree/main/pkg/analyzer_plugin

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  analyzer: ^4.1.0
  collection: ^1.15.0
  dart_style: ^2.2.1
  pub_semver: ^2.0.0
  yaml: ^3.1.0

dev_dependencies:
  lints: ^1.0.0
  meta: ^1.8.0
  path: ^1.8.2
  test_reflective_loader: ^0.2.1
  test: ^1.21.4
